rawg_dbt:
  outputs:
    dev:
      type: duckdb
      path: ../rawg_data.duckdb
      schema: main
      threads: 1
    prod:
      type: duckdb
      path: ../rawg_data.duckdb
      schema: main
      threads: 4
  target: dev